// <auto-generated />
namespace _1911065673_NguyenDucThong_BigSchool.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CreateTableCourse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateTableCourse));
        
        string IMigrationMetadata.Id
        {
            get { return "202203140935328_CreateTableCourse"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
